### ISSUE TITLE
Set nbgallery.url

### ISSUE THREAD

**Issue by kylekyle** [nbgallery/nbgallery-extensions#2]
The pip installation should really drop (or update) the ~/.jupyter/nbconfig/common.json and set the nbgallery.url key to "https://nb.gallery", or the extensions will never load outside of the docker image (where we provide that config). 

Anyone know if that's possible in pip?

**Comment by rfestag** [comment]
I don't know, but I'm not sure I like that anyways. If some other extensions put settings in common.js, then we would be blowing those away on existing installs. Not to mention updates would revert it if somebody changes it. Instead, I'd lean towards a programmatic default...Check if the value exists, if not, set it to some hard coded default.

**Comment by kylekyle** [comment]
Yeah, that was the original approach. A programmatic default won't cover multiple contexts. How about just updating the config instead of blowing it away?

**Comment by rfestag** [comment]
If it's possible, sure.  Although I'm not a huge fan of making changes outside of the package, that is certainly less bad. That said, can we either check multiple contexts or always check the same context?

**Comment by psychemedia** [comment]
I'm trying to use this extension in the minimal container ( `docker run --rm -p 8111:443 nbgallery/jupyter-alpine`) and the extension doesn't load in a notebook. The error looks to be a baked in domain (when I run the container, I access it visa https://localhost:PORT).

```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
require.js?v=6da8be361b9ee26c5e721e76c6d4afce:140 Uncaught Error: Script error for "https://nb.gallery/integration/gallery-common.js"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:165)
    at HTMLScriptElement.onScriptError (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1732)
utils.js:37 Loading extension: jupyter-js-widgets/extension
docker-gallery-notebook.js?v=20181204163100:18 loading gallery-notebook integration from https://nb.gallery
extension.js:102 loaded widgets
gallery-notebook.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
require.js?v=6da8be361b9ee26c5e721e76c6d4afce:140 Uncaught Error: Script error for "https://nb.gallery/integration/gallery-notebook.js"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:165)
    at HTMLScriptElement.onScriptError (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1732)
:8111/static/base/images/favicon-notebook.ico:1 
```

**Comment by jeffyjefflabs** [comment]
The docker image and this extension are configured to load additional javascript from an instance of the nbgallery rails app.  You are correct that `nb.gallery` is the default baked-in domain, but that domain doesn't exist.  You should override it by setting the environment variable NBGALLERY_URL to the location of your nbgallery rails app when you start up the `nbgallery/jupyter-alpine` container (`-e` option to `docker run`).  [Here's the code](https://github.com/nbgallery/jupyter-alpine/blob/master/config/jupyter/jupyter_notebook_config.py#L32) in the docker image that looks for that environment variable.

**Comment by jeffyjefflabs** [comment]
There's always going to be some manual configuration involved, so I think the new [configuration script](https://github.com/nbgallery/nbgallery-extensions#jupyter-configuration) suffices here.
