### ISSUE TITLE
Gallery drop-down menu not available 

### ISSUE THREAD

**Issue by ezhilal** [nbgallery/nbgallery-extensions#4]
I followed the guide to install and enable jupyter_nbgallery in my jupyter server:

"pip install jupyter_nbgallery -U
jupyter serverextension enable --py jupyter_nbgallery
jupyter nbextension install --py jupyter_nbgallery
jupyter nbextension enable jupyter_nbgallery --py "

When starting the server, it states that the extension jupyter_nbgallery is enabled, however I cannot see it in the notebook itself. I expected the "Gallery" drop-down menu. 
Is there something I am missing?

**Comment by jeffyjefflabs** [comment]
Do you have an instance of nbgallery running?  The extension on the Jupyter side actually doesn't contain all the code; it downloads the javascript for the menu from nbgallery.  There are also a few manual configuration steps described in the nbgallery extension [here](https://github.com/nbgallery/nbgallery/blob/master/docs/jupyter_integration.md#manual-configuration) -- sorry, we should make that more obvious from the README in this repo.

Side note: parts of the extension (I think just the server extension) don't work in the latest version of Jupyter, due to changes in tornado.  We're working on a refactoring that will fix that as well as clean up how all the javascript works.

You could also try using our [jupyter-alpine](https://github.com/nbgallery/jupyter-alpine) docker image, which has the extension baked in; you just need to set an environment variable with the location of your nbgallery instance.  However note that we're retiring that image in favor of one built off the official Jupyter project's base image, in conjunction with the refactoring I mentioned above.  There are some pieces of it [in this repo](https://github.com/nbgallery/docker-images) but it's not complete yet.

**Comment by ezhilal** [comment]
Thank you for your answer!
Yes I actually follows the configuration steps as well. 
I realized that it was not a nbgallery/jupyter issue but an issue due to secured and unsafe protocols. So problem is solved here.

However I am now trying to set up an jupyterlab instance instead of the jupyter notebook instance. Do you have any experience with that or any recommendations? 
I have seen the information about the migration away form the jupyter-alpine image but didnt get my head around the usage of the new image. Thats why I have been processing with the old one.

**Comment by ezhilal** [comment]
Regarding the secured and unsafe protocols;
How do I add certificates to the nbgallery service, so both nbgallery and jupyter are using https?

**Comment by jeffyjefflabs** [comment]
Ah yes, either both have to be http or both https for the cross-site javascript to work.  If you don't actually need https, you can run the jupyter-alpine image and specify a non-secure entrypoint; see for example our [docker compose](https://github.com/nbgallery/nbgallery/blob/master/docker-compose-with-jupyter.yml) or our [insecure startup script](https://github.com/nbgallery/jupyter-alpine/blob/master/util/jupyter-notebook-insecure-for-testing-only).

If you do want both secure, jupyter-alpine's [default entrypoint](https://github.com/nbgallery/jupyter-alpine/blob/master/util/jupyter-notebook-secure) shows how to generate a self-signed certificate and use that with Jupyter.  For nbgallery, there are several options for running secure.  In development we use puma with a self-signed cert, similar to [this gist](https://gist.github.com/tadast/9932075).  In production it depends how you're running rails (puma, passenger, apache, nginx, etc) - [this article](https://www.pluralsight.com/guides/using-https-with-ruby-on-rails) talks about some of the options but I would just google your specific environment.

Re: our new docker image - it's not ready yet... in particular, it doesn't have any of the nbgallery integrations yet.  It will default to a non-secure entrypoint, though; we anticipate that users would either be running it behind an https proxy or else building their own docker image with ours as a base.

**Comment by ezhilal** [comment]
I tried now to add certificates to nbgallery using puma:
1) create privatekey(called 'xxx.key') and certificate (called 'cert.pem')
2) added to the Dockerfile : 
_COPY xxx.key ./
COPY cert.pem ./_
3) added to the docker-entrypoint.sh: 
_bundle exec rails server -b 'ssl://0.0.0.0:3000?key=/usr/src/nbgallery/xxx.key&cert=/usr/src/nbgallery/cert.pem'_
4) rebuilt the image

There occured the problem: Rails Server (Puma): _SSL not available in this build (StandardError_)
I changed the ruby version form 2.3 to 2.4 and had to change the "mysql-client" to "default-mysql-client" in the Dockerfile.
I thought I am following your guide above, but somehow it doesn't work (_nbgallery_nbgallery_1 exited with code 1_). Are my steps correct?

**Comment by jeffyjefflabs** [comment]
Never seen that, but sounds like this: https://github.com/puma/puma/issues/971

**Comment by ezhilal** [comment]
Thank you for the link!
I tried now the following: Started the docker, uninstalled puma, installed openssl and installed puma again- as recommended in the link. But I still get the same error. 
When executing : _bundle exec rails server -b 'ssl://0.0.0.0:3000?key=/usr/src/nbgallery/xxx.key&cert=/usr/src/nbgallery/cert.pem'_, I get the following output:
_Loading extension config: propose_org_as_tag.yml
=> Booting Puma
=> Rails 4.2.11 application starting in production on http://ssl://0.0.0.0:3000?key=/usr/src/nbgallery/security.key&cert=/usr/src/nbgallery/cert.pem:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server_

Shouldnt I expect: _https://0.0.0.0:3000?key=..._ ?

**Comment by jeffyjefflabs** [comment]
Try using `puma` on the command line directly, instead of `rails server`.  I think the `-b` option for rails only accepts the IP, while puma will take that whole ssl string -- see also https://puma.io/puma/

**Comment by ezhilal** [comment]
Thank you, Jeff! This is working finally!!

**Comment by jeffyjefflabs** [comment]
Awesome!
