### ISSUE TITLE
Jupyter lab

### ISSUE THREAD

**Issue by ezhilal** [nbgallery/nbgallery-extensions#5]
I want to use jupyter lab together with the nbgallery implementation. I managed to load the notebooks from nbgallery to jupyter lab but I am missing the nbgallery extension within jupyterlab. 
Using jupyter notebooks (jupyter-alpine image), where is the extension loaded for the frontend? 
You mentioned in an other issue that a javascript is loaded from nbgallery.

**Comment by jeffyjefflabs** [comment]
Yeah, unfortunately UI extensions in Lab use a completely new framework, so "classic" extensions have to be rewritten. We haven't started to look at that yet.

As for how this extension works, on the Jupyter side the notebook extension code is [here](https://github.com/nbgallery/nbgallery-extensions/blob/master/jupyter_nbgallery/static/docker-gallery-notebook.js).  If you browse through that, you'll see that the bulk of the code is actually downloaded from `<nbgallery url>/integration/gallery-notebook.js` as well as anything configured in `extra_integration`.  Those javascripts all live [here in the nbgallery codebase](https://github.com/nbgallery/nbgallery/tree/master/public/integration).  That's all going to change, though.  We originally did it that way so we could update the extensions from the nbgallery side.  In practice we didn't need to do that very often, so we're going to move all that code into this repo as proper Jupyter extensions that can be enabled individually.

**Comment by jeffyjefflabs** [comment]
I'm going to close this - work on nbgallery extensions for JupyterLab is happening in a new repo - https://github.com/nbgallery/lab-extensions
